version: '3.1'
services:
  vaultionizer_app:
    container_name: vaultionizer_app
    image: vaultionizer_app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgres_vault
    environment:
      - VAULT_ENABLE_SSL=false
      - VAULT_DB_USER=postgres
      - VAULT_DB_PASSWORD=password
      - VAULT_DB_DATABASE=mydb
      - VAULT_DB_HOST=postgres_vault
  postgres_vault:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb