version: '3.1'
services:
  vaultionizer_app:
    container_name: vaultionizer_app
    image: vaultionizer_app
    build: ./
    ports:
      - "443:443"
    depends_on:
      - postgres_vault
  postgres_vault:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mydb